# Generated by Django 4.0.6 on 2022-07-16 07:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('planlog', '0003_added_member_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('card_order', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, null=True, size=None)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_lists', to='planlog.board')),
            ],
            options={
                'db_table': 'lists',
            },
        ),
    ]
