# Generated by Django 4.0.6 on 2022-07-18 16:27

from django.db import migrations


def add_board_owner_to_board_member(apps, schema_editor):

    Board = apps.get_model('planlog', 'Board')
    boards = Board.objects.all()
    Member = apps.get_model('planlog', 'Member')

    for board in boards:
        try:
            Member.objects.get(board=board, user=board.user)
        except Member.DoesNotExist:
            Member.objects.create(board=board, user=board.user)

class Migration(migrations.Migration):

    dependencies = [
        ('planlog', '0005_added_card_model'),
    ]

    operations = [
        migrations.RunPython(add_board_owner_to_board_member, migrations.RunPython.noop),
    ]
