name: Backend CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  testing-job:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: planlog
          POSTGRES_PASSWORD: planlog
          POSTGRES_DB: planlog_testing
        ports:
          - 5432:5432
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
           python-version: 3.10
      - name: Install the dependencies
        run: pip install -r requirements.txt
      - name: Run test
        env:
          DJANGO_SETTINGS_MODULE: planlog.settings.testing
          PG_NAME: planlog_testing
          PG_USER: planlog
          PG_PASSWORD: planlog
        run: python manage.py test
